# Generated by Django 5.0.2 on 2024-03-05 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teacher_book_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='app.teacher'),
        ),
    ]
