# Generated by Django 5.0.2 on 2024-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAppSignal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('signal_data', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
