# Generated by Django 5.0.2 on 2024-03-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_driverappsignal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverappsignal',
            name='device_imei',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='driverappsignal',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
