# Generated by Django 5.0.2 on 2024-03-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_driverappsignal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
