# Generated by Django 5.0.2 on 2024-03-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_book_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
