# Generated by Django 5.0.2 on 2024-03-18 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_driverappsignal_latitude_driverappsignal_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverappsignal',
            name='signal_data',
        ),
        migrations.AddField(
            model_name='driverappsignal',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driverappsignal',
            name='driver_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driverappsignal',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
