# Generated by Django 5.0.2 on 2024-03-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_driverappsignal_signal_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'journey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverJourney',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('journey_id', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
