# Generated by Django 5.0.2 on 2024-03-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_book_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverjourney',
            name='driver_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driverjourney',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverjourney',
            name='journey_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
