# Generated by Django 5.0.2 on 2024-03-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_driverjourney_driver_id_alter_driverjourney_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverjourney',
            name='driver_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driverjourney',
            name='journey_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
