# Generated by Django 5.0.2 on 2024-03-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_driverjourney_driver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverjourney',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
