# Generated by Django 5.0.2 on 2024-03-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_driverjourney_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverjourney',
            name='active',
        ),
    ]
