# Generated by Django 5.0.2 on 2024-03-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_driverjourney_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverjourney',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
