# Generated by Django 5.0.2 on 2024-03-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_driverjourney_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
    ]
