# Generated by Django 5.0.2 on 2024-03-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start_type', models.CharField(max_length=255)),
                ('end_type', models.CharField(max_length=255)),
                ('start_facility', models.CharField(max_length=255)),
                ('end_facility', models.CharField(max_length=255)),
                ('start_village_id', models.CharField(max_length=255)),
                ('start_port_id', models.CharField(max_length=255)),
                ('end_port_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
    ]
