# Generated by Django 5.0.2 on 2024-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareFacility',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
            ],
            options={
                'db_table': 'healthcare_facility',
                'managed': False,
            },
        ),
    ]
